//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class laptop
    {
        public int Id { get; set; }
        public string laptopname { get; set; }
        public string cpu { get; set; }
        public int cpuperf { get; set; }
        public string gpu { get; set; }
        public int gpuperf { get; set; }
        public int ram { get; set; }
        public int storage { get; set; }
        public int temperature { get; set; }
        public int price { get; set; }
        public int sound { get; set; }
        public string screen { get; set; }
        public string afflink { get; set; }
    }
}
